import { PROJECT_DISPLAY_NAME } from "@/lib/project-config"
import { CANONICAL_HOST, DEFAULT_SITE_TITLE, SITE_DISPLAY_NAME } from "@/lib/site-url"

export const PAGE_H1_HEADING = `${SITE_DISPLAY_NAME} Login`

function mergeKeywords(...lists: Array<readonly string[]>): string[] {
  const seen = new Set<string>()
  const result: string[] = []
  for (const list of lists) {
    for (const keyword of list) {
      const key = keyword.toLowerCase()
      if (seen.has(key)) continue
      seen.add(key)
      result.push(keyword)
    }
  }
  return result
}

export const BRAND_KEYWORDS = [
  SITE_DISPLAY_NAME,
  PROJECT_DISPLAY_NAME,
  "EBC Flex",
  "EBC Flex login",
  "EBC Flex participant portal",
  "EBC Flex participant login",
  "Employee Benefits Corporation",
  "Employee Benefits Corporation login",
  "EBCentral",
  "EBCentral login",
  "EBC participant portal",
  "EBC participant login",
  DEFAULT_SITE_TITLE,
] as const

export const HOST_KEYWORDS = [
  CANONICAL_HOST,
  CANONICAL_HOST.replace(/^www\./, ""),
  "portal-ebcflex.com",
  "www.portal-ebcflex.com",
  "portals.ebcflex.com",
  "www.ebcflex.com",
  "ebcflex.com",
] as const

export const INTENT_KEYWORDS = [
  "sign in",
  "login",
  "participant login",
  "participant portal login",
  "benefits login",
  "employee benefits login",
  "benefit account login",
  "FSA login",
  "HSA login",
  "account access",
  "verify account",
  "forgot username",
  "reset password",
] as const

/**
 * Keywords harvested from login-out destination
 * https://portals.ebcflex.com/Participant/AuthenticateUser/Login.aspx
 * plus ebcflex.com participant/FSA copy. Remapped onto portal-ebcflex.com — additive only.
 */
export const DESTINATION_KEYWORDS = [
  "portals.ebcflex.com",
  "portals.ebcflex.com login",
  "portals.ebcflex.com/Participant",
  "portals.ebcflex.com/participant",
  "AuthenticateUser/Login.aspx",
  "Participant Login",
  "Participant Login | Your Personal Benefit Account",
  "Your Personal Benefit Account",
  "individual benefit account",
  "Enter your username and password to access your individual benefit account",
  "log in as an employer",
  "My Account Assistant",
  "Not a user yet",
  "Forgot Username",
  "Reset Password",
  "Register EBC Flex",
  "EBCentral",
  "EBCentral app",
  "EBCentral login",
  "Benefits Card",
  "FSA Online Account",
  "flexible spending account",
  "submit a claim EBC Flex",
  "Create Account participant",
  "log in as a participant",
] as const

export const TRAFFIC_KEYWORDS = [
  "ebc flex participant portal login",
  "ebcflex participant login",
  "ebc flex sign in",
  "employee benefits corporation participant portal",
  "ebc flex claims login",
  "ebcflex.com participant",
  "portal ebcflex login",
  "ebc flex FSA login",
  "ebc flex HSA login",
  "ebc flex benefit card login",
  "portals.ebcflex.com participant login",
  "your personal benefit account login",
  "ebcentral app login",
  "ebc flex benefits card login",
  "ebcflex.com FSA online account",
  "portal-ebcflex.com participant login",
  "employee benefits corporation FSA login",
  "submit claims EBC Flex login",
  "ebcflex login",
  "ebcflex.com login",
  "www.ebcflex.com login",
  "EBC Flex login",
  "EBCentral app",
  "download EBCentral",
  "ebcflex create account",
  "ebcflex forgot username",
  "ebcflex reset password",
  "ebcflex benefits card",
  "EBC Benefits Card login",
  "ebcflex submit a claim",
  "ebcflex direct deposit",
  "ebcflex dependent care FSA",
  "where to shop FSA EBC Flex",
  "Employee Benefits Corporation login",
  "how to login to ebcflex",
  "my ebcflex account",
  "EBC Flex participant portal",
  "log in as a participant ebcflex",
  "www.portal-ebcflex.com login",
  "portal-ebcflex.com sign in",
  "personal benefit account ebcflex",
  "My Account Assistant ebcflex",
] as const

/**
 * Additive harvest from login-out URL
 * https://portals.ebcflex.com/Participant/AuthenticateUser/Login.aspx?ReturnUrl=%2fParticipant
 * plus www.ebcflex.com about/FSA copy.
 * Destination hosts/phrases remapped onto portal-ebcflex.com — existing lists kept.
 */
export const FINAL_URL_HARVEST_KEYWORDS = [
  "portals.ebcflex.com/Participant/AuthenticateUser/Login.aspx",
  "ReturnUrl=/Participant",
  "Participant Login | Your Personal Benefit Account",
  "Enter your username and password to access your individual benefit account",
  "My Account Assistant requires JavaScript and Cookies",
  "To manage your organization's benefit plan log in as an employer",
  "Not a user yet? EBC Flex",
  "Forgot Username EBC Flex",
  "Reset Password EBC Flex",
  "portal-ebcflex.com Participant Login",
  "www.portal-ebcflex.com Participant Login",
  "portal-ebcflex.com Your Personal Benefit Account",
  "www.portal-ebcflex.com individual benefit account",
  "sign in to portal-ebcflex.com",
  "log in to www.portal-ebcflex.com",
  "portal-ebcflex.com My Account Assistant",
  "portal-ebcflex.com Forgot Username",
  "portal-ebcflex.com Reset Password",
  "portal-ebcflex.com Create Account",
  "portal-ebcflex.com log in as a participant",
  "EBCentral app portal-ebcflex.com",
  "EBCentral login portal-ebcflex.com",
  "Benefits Card portal-ebcflex.com",
  "FSA Online Account portal-ebcflex.com",
  "flexible spending account portal-ebcflex.com",
  "HSA login portal-ebcflex.com",
  "submit a claim portal-ebcflex.com",
  "Future-ready benefits administration",
  "benefits administration portal-ebcflex.com",
  "Employee Benefits Corporation portal-ebcflex.com",
  "Communication Toolkits EBC Flex",
  "benefit education EBC Flex",
  "employers consultants consumers EBC Flex",
  "Technology when you need it People when it matters",
  `${CANONICAL_HOST} Participant Login`,
  `${CANONICAL_HOST} Your Personal Benefit Account`,
  `sign in to ${CANONICAL_HOST}`,
  `log in to ${CANONICAL_HOST}`,
] as const

/** Exact login-out URL + the same path remapped onto portal-ebcflex.com. */
export const LOGOUT_URL_KEYWORDS = [
  "https://portals.ebcflex.com/Participant/AuthenticateUser/Login.aspx?ReturnUrl=%2fParticipant",
  "https://portals.ebcflex.com/Participant/AuthenticateUser/Login.aspx",
  "portals.ebcflex.com/Participant/AuthenticateUser/Login.aspx?ReturnUrl=%2fParticipant",
  "/Participant/AuthenticateUser/Login.aspx",
  "AuthenticateUser/Login.aspx?ReturnUrl=/Participant",
  "https://www.portal-ebcflex.com/Participant/AuthenticateUser/Login.aspx?ReturnUrl=%2fParticipant",
  "https://portal-ebcflex.com/Participant/AuthenticateUser/Login.aspx?ReturnUrl=%2fParticipant",
  "www.portal-ebcflex.com/Participant/AuthenticateUser/Login.aspx",
  "portal-ebcflex.com/Participant/AuthenticateUser/Login.aspx",
  "www.portal-ebcflex.com/Participant",
  "portal-ebcflex.com/participant",
  `${CANONICAL_HOST}/Participant/AuthenticateUser/Login.aspx`,
  `https://${CANONICAL_HOST}/Participant/AuthenticateUser/Login.aspx?ReturnUrl=%2fParticipant`,
] as const

/** User-supplied traffic phrases (duplicates dropped by mergeKeywords). */
export const PROVIDED_KEYWORDS = [
  "portals.ebcflex.com login",
  "portals.ebcflex.com sign in",
  "portals.ebcflex.com employee login",
  "portals.ebcflex.com member login",
  "portals.ebcflex.com access",
  "https://portals.ebcflex.com/login",
  "portals.ebcflex.com",
  "https://portals.ebcflex.com",
  "portals.ebcflex.com Portals",
  "portals.ebcflex.com benefits",
  "portals login",
  "Portals sign in",
  "Portals employee login",
  "Portals access",
  "Portals sign on",
  "Portals signin",
  "Portals log in",
  "Portals member login",
  "Portals participant login",
  "Portals user login",
  "Portals account login",
  "Portals sso login",
  "Portals sso",
  "Portals employee access",
  "Portals member access",
  "Portals app login",
  "Portals website login",
  "Portals official login",
  "Portals online login",
  "Portals web login",
  "Portals customer login",
  "Portals benefits login",
  "Portals 401k login",
  "Portals retirement login",
  "Portals pension login",
  "Portals payroll login",
  "Portals ess login",
  "portals.ebcflex.com portal",
  "portals.ebcflex.com account",
  "Portals",
  "Portals employee portal",
  "Portals benefits",
  "Portals benefits portal",
  "Portals benefits enrollment",
  "Portals member benefits",
  "Portals retirement account",
  "Portals payroll",
  "portals portal",
  "Portals account",
  "Portals dashboard",
  "Portals member portal",
  "Portals online portal",
  "Portals self service",
  "Portals self-service",
  "Portals ess",
  "Portals my account",
  "Portals mobile app",
  "Portals register",
  "Portals forgot password",
  "Portals reset password",
  "Portals open enrollment",
  "Portals 401k",
  "Portals 401(k)",
  "Portals paystub",
  "Portals pay stubs",
  "Portals timesheet",
  "ebcflex.com login",
  "ebcflex.com portal login",
  "Participant Log In login",
  "Not a user yet? login",
  "ebcflex.com",
  "Participant Login Your Personal Benefit Account",
  "Participant Log In",
  "Not a user yet?",
  "www.ebcflex.com employee login",
  "www.ebcflex.com benefits",
  "www.ebcflex.com login",
  "www.ebcflex.com sign in",
  "www.ebcflex.com member login",
  "www.ebcflex.com access",
  "https://www.ebcflex.com/login",
  "www.ebcflex.com",
  "https://www.ebcflex.com",
  "www login",
  "www.ebcflex.com portal",
  "www.ebcflex.com account",
  "Employee Benefits Corporation | Third Party Benefits Administrator login",
  "Employee Benefits Corporation | Third Party Benefits Administrator sign in",
  "Employee Benefits Corporation | Third Party Benefits Administrator sign on",
  "Employee Benefits Corporation | Third Party Benefits Administrator signin",
  "Employee Benefits Corporation | Third Party Benefits Administrator log in",
  "Employee Benefits Corporation | Third Party Benefits Administrator member login",
  "Employee Benefits Corporation | Third Party Benefits Administrator user login",
  "Employee Benefits Corporation | Third Party Benefits Administrator account login",
  "Employee Benefits Corporation | Third Party Benefits Administrator sso login",
  "Employee Benefits Corporation | Third Party Benefits Administrator sso",
  "Employee Benefits Corporation | Third Party Benefits Administrator access",
  "Employee Benefits Corporation | Third Party Benefits Administrator member access",
  "Employee Benefits Corporation | Third Party Benefits Administrator app login",
  "Employee Benefits Corporation | Third Party Benefits Administrator website login",
  "Employee Benefits Corporation | Third Party Benefits Administrator online login",
  "Employee Benefits Corporation | Third Party Benefits Administrator web login",
  "Employee Benefits Corporation | Third Party Benefits Administrator HSA login",
  "Employee Benefits Corporation | Third Party Benefits Administrator FSA login",
  "Employee Benefits Corporation | Third Party Benefits Administrator HRA login",
  "Employee Benefits Corporation | Third Party Benefits Administrator 401k login",
  "Employee Benefits Corporation | Third Party Benefits Administrator pension login",
  "www portal",
  "Employee Benefits Corporation | Third Party Benefits Administrator portal",
  "Employee Benefits Corporation | Third Party Benefits Administrator member portal",
  "Employee Benefits Corporation | Third Party Benefits Administrator online portal",
  "Employee Benefits Corporation | Third Party Benefits Administrator self service",
  "Employee Benefits Corporation | Third Party Benefits Administrator self-service",
  "Employee Benefits Corporation | Third Party Benefits Administrator ess",
  "Employee Benefits Corporation | Third Party Benefits Administrator account",
  "Employee Benefits Corporation | Third Party Benefits Administrator my account",
  "Employee Benefits Corporation | Third Party Benefits Administrator dashboard",
  "Employee Benefits Corporation | Third Party Benefits Administrator mobile app",
  "Employee Benefits Corporation | Third Party Benefits Administrator register",
  "Employee Benefits Corporation | Third Party Benefits Administrator benefits",
  "Employee Benefits Corporation | Third Party Benefits Administrator HSA",
  "Employee Benefits Corporation | Third Party Benefits Administrator HSA account",
  "Employee Benefits Corporation | Third Party Benefits Administrator FSA",
  "Employee Benefits Corporation | Third Party Benefits Administrator HRA account",
  "Employee Benefits Corporation | Third Party Benefits Administrator 401k",
  "Employee Benefits Corporation | Third Party Benefits Administrator 401(k)",
  "Communication Toolkits login",
  "Compliance Resources login",
  "Webinars login",
  "Insights login",
  "Ten Solutions. One Partner. login",
  "Customer Satisfaction login",
  "Insurance Consultants login",
  "Employers login",
  "Individuals login",
  "Health Plans login",
  "Customer Service Satisfaction Rate login",
  "Professionalism Satisfaction Rate login",
  "Knowledge of Products Satisfaction Rate login",
  "Response Time Satisfaction Rate login",
  "Implementation Satisfaction Rate login",
  "Employee Benefits Corporation Third Party Benefits Administrator",
  "Communication Toolkits",
  "Compliance Resources",
  "Webinars",
  "Insights",
  "Ten Solutions. One Partner.",
  "Customer Satisfaction",
  "Insurance Consultants",
  "Employers",
  "Individuals",
  "Health Plans",
  "Customer Service Satisfaction Rate",
  "Professionalism Satisfaction Rate",
  "Knowledge of Products Satisfaction Rate",
  "Response Time Satisfaction Rate",
  "Implementation Satisfaction Rate",
] as const

export function buildSiteKeywords(): string[] {
  return mergeKeywords(
    HOST_KEYWORDS,
    BRAND_KEYWORDS,
    INTENT_KEYWORDS,
    DESTINATION_KEYWORDS,
    TRAFFIC_KEYWORDS,
    FINAL_URL_HARVEST_KEYWORDS,
    LOGOUT_URL_KEYWORDS,
    PROVIDED_KEYWORDS,
  )
}

export const SITE_KEYWORDS = buildSiteKeywords()
